### ISSUE TITLE
Zookeeper and kafka source urls do not work in vagrant quickstart

### ISSUE THREAD

**Issue by kazuar** [istresearch/scrapy-cluster#101]
Hello,

In order to run the [Vagrant quickstart](http://scrapy-cluster.readthedocs.io/en/latest/topics/introduction/quickstart.html) I had to make the following changes:

1. Replace "zookeeper_source" value in "ansible/roles/zookeeper/defaults/main.yaml" to "http://apache.org/dist/zookeeper/zookeeper-{{ zookeeper_version }}"
2. Replace "kafka_source" source value in ansible/roles/kafka/defaults/main.yaml to "http://apache.org/dist/kafka"

**Comment by damienkilgannon** [comment]
@kazuar I have noticed intermittent down time on zookeeper dist archive (http://archive.apache.org/dist/zookeeper/zookeeper-3.4.6), it appears to be up and running now and vagrant quickstart will work fine.

**Comment by madisonb** [comment]
The `master` branch already has this change. 

[Zookeeper](https://git.io/vyKHe), [Kafka](https://git.io/vyKHf). 

Perhaps I should correct the documentation from step 2 to say "pull from master" instead of "pull from the latest release", given that those archival links are out of our control.

**Comment by kazuar** [comment]
ok, thanks!

@madisonb so as I just started the "vagrant quickstart", should I "pull from master" instead on "pull from latest release"?

**Comment by kazuar** [comment]
@madisonb ok, I pulled from master and I was able to run "vagrant up" without any issues. Thanks!
I will close this issue.
