### ISSUE TITLE
Can Scrapy Cluster work with Scrapy 1.3.3?

### ISSUE THREAD

**Issue by wenxzhen** [istresearch/scrapy-cluster#104]
I found in the requirements.txt, the Scrapy is binding to 1.0.5. Does it work with Scrapy 1.3?

**Comment by kazuar** [comment]
Scrapy 1.3.3 is supported in Release-1.2 ([requirements](https://github.com/istresearch/scrapy-cluster/blob/release-1.2/requirements.txt))

**Comment by madisonb** [comment]
Closing.
