### ISSUE TITLE
kafka-monitor tests has been "frozen" for unknown reason/cloudera cluster

### ISSUE THREAD

**Issue by waybackse** [istresearch/scrapy-cluster#111]
I'm using "fresh" setup of cluster based on cloudera solution.     
> cd scrapy-cluster/kafka-monitor && python tests/online.py -v
test_feed (__main__.TestKafkaMonitor) ... (I just see that line, no more)

>  cat localsettings.py
KAFKA_HOSTS = ['node1.cluster:9092','node2.cluster:9092','node3.cluster:9092']

> /usr/bin/kafka-topics  --zookeeper node3.cluster:2181 --list
..skipped...
17/04/01 17:10:08 INFO zkclient.ZkClient: zookeeper state changed (SyncConnected)
__consumer_offsets
demo.incoming_test
17/04/01 17:10:08 INFO zkclient.ZkEventThread: Terminate ZkClient event thread.
17/04/01 17:10:08 INFO zookeeper.ZooKeeper: Session: 0x25b2a7ead190001 closed
17/04/01 17:10:08 INFO zookeeper.ClientCnxn: EventThread shut down

All tests from https://github.com/dpkp/kafka-python has been passed and examples of code working for me
Any suggestions?

**Comment by madisonb** [comment]
My guess is that your Kafka cluster is not set up properly. If you can give me instructions for how to reproduce this in my vagrant machine or in a local set up, I can try to help.

Otherwise, this is a [custom setup](http://scrapy-cluster.readthedocs.io/en/latest/topics/contributing.html#raising-issues) and I would like to close this.

**Comment by waybackse** [comment]
If my cluster has broken setup, why all tests from kafka-python has been passed? Also  I wrote small tests for consumer and producer and everything work as expected.
I thinks we have a bug related to cloudera clusters.
If everyone have an experience with cloudera any help will be appreciated. Please do not close this ticket.

**Comment by waybackse** [comment]
I found a bug. You haven't using **iter_timeout.** in consumer constructor. If  topic is empty script will wait forever for any any new messages.

https://github.com/dpkp/kafka-python/blob/1937ce59b4706b44091bb536a9b810ae657c3225/kafka/consumer/simple.py#L100
