### ISSUE TITLE
Does redis-monitor can connect redis with password?

### ISSUE THREAD

**Issue by movingheart** [istresearch/scrapy-cluster#114]
`class RedisMonitor(object):

    def __init__(self, settings_name, unit_test=False):
        '''
        @param settings_name: the local settings file name
        @param unit_test: whether running unit tests or not
        '''
        self.settings_name = settings_name
        self.redis_conn = None
        self.wrapper = SettingsWrapper()
        self.logger = None
        self.unit_test = unit_test
        self.my_uuid = str(uuid.uuid4()).split('-')[4]

    def setup(self, level=None, log_file=None, json=None):
        '''
        Load everything up. Note that any arg here will override both
        default and custom settings

        @param level: the log level
        @param log_file: boolean t/f whether to log to a file, else stdout
        @param json: boolean t/f whether to write the logs in json
        '''
        self.settings = self.wrapper.load(self.settings_name)

        my_level = level if level else self.settings['LOG_LEVEL']
        # negate because logger wants True for std out
        my_output = not log_file if log_file else self.settings['LOG_STDOUT']
        my_json = json if json else self.settings['LOG_JSON']
        self.logger = LogFactory.get_instance(json=my_json,
                                              stdout=my_output, level=my_level,
                                              name=self.settings['LOGGER_NAME'],
                                              dir=self.settings['LOG_DIR'],
                                              file=self.settings['LOG_FILE'],
                                              bytes=self.settings['LOG_MAX_BYTES'],
                                              backups=self.settings['LOG_BACKUPS'])

        self.redis_conn = redis.StrictRedis(host=self.settings['REDIS_HOST'],
                                      port=self.settings['REDIS_PORT'],
                                      db=self.settings['REDIS_DB'])`
This code can not connect redis had password.

**Comment by madisonb** [comment]
I will gladly accept a PR to fix this, you need to update the following:
- The code itself to accept a `REDIS_PASSWORD`, default is `None`
- the settings.py file
- the docker settings.py file and ensure it is an environment variable
- documentation for the new setting

If you can fix it for the Redis Monitor, given that all other components need to talk to Redis as well, the same updates will also apply to the Crawler, Rest Service, and Kafka Monitor.

**Comment by aafeher** [comment]
I made a solution to use password in redis connection.
PR #195
