### ISSUE TITLE
Should "Found url to crawl" logging string be unicode?

### ISSUE THREAD

**Issue by py-in-the-sky** [istresearch/scrapy-cluster#119]
I'm inquiring about the DEBUG logging statement [here](https://github.com/istresearch/scrapy-cluster/blob/master/crawler/crawling/distributed_scheduler.py#L504) in hopes to better understand scrapy-cluster. Should this logging string be a unicode string?

When I submit a URL with unicode characters (e.g., "https://www.legitscript.com/blog/2017/03/「日本語だから大丈夫？」ベストケンコーの新た/") or inline unicode code points (e.g., "https://www.legitscript.com/blog/2017/03/\u300c\u65e5\u672c\u8a9e\u3060\u304b\u3089\u5927\u4e08\u592b\uff1f\u300d\u30d9\u30b9\u30c8\u30b1\u30f3\u30b3\u30fc\u306e\u65b0\u305f/"), an exception is thrown from the logging statement:

```
...
  File "/vagrant/crawler/crawling/distributed_scheduler.py", line 509, in next_request
    .format(url=item['url']))
exceptions.UnicodeEncodeError: 'ascii' codec can't encode characters in position 41-62: ordinal not in range(128)
```

Or, on the other hand, should I make sure not to submit unicode URLs?

When I change the logging string to unicode (by simply prepending a `u`) and submit a URL with unicode characters, my crawl succeeds; the problem _seems_ to disappear. All tests still pass, too, after I prepend the `u`.

IIRC, `CustomLxmlLinkExtractor` returns links found as unicode types, rather than normal Python 2 strings. I'm curious whether, from a consistency standpoint, URLs should be treated as unicode throughout the codebase.

Thanks for your response and for your work on this project!

**Comment by madisonb** [comment]
The debugging statement is just that, a debug log I threw into the code to try to trace items through the system. I agree with you in that it should be sanitized and not throw errors when given Unicode data.

In regards to the custom link extractor, that is modeled closely after the default Scrapy one (at least it was when that code was created), and I didn't change it's underlying behavior. I only added some logic to not throw errors when encountering bad Unicode data.

If you would like to PR onto the `dev` branch I would be happy to accept an update for the Unicode handling if you can get to it before I can.

**Comment by madisonb** [comment]
PR merged, closing ticket.
