### ISSUE TITLE
Scrapy Cluster Utils Packaging

### ISSUE THREAD

**Issue by madisonb** [istresearch/scrapy-cluster#13]
It would be nice if we could bundle the `utils` folder into its own package so that we no longer need symlinks or to duplicate code when scrapy cluster is deployed across multiple machines.

This issue should also cover the documentation of said `sc-utils` package and getting it on pypi.

**Comment by jasonrhaas** [comment]
Starting work on this.  The plan is to package up all the utils under the `sc-utils` name and change the code to import each module as needed.  For example, `from sc-utils import log_factory`.

**Comment by jasonrhaas** [comment]
The packaging is complete with pull request #21.  Would like to host `scutils` on PyPi so that it doesn't have to be built manually.  Can do the PyPi packaging as part of this issue or open a new one.

**Comment by madisonb** [comment]
Green light to put it up, just reference that the documentation for `0.0.1` is not quite ready yet and will be released with SC 1.1.

Do it as apart of this issue, and update the Readme, reqs.txt, etc for better installation instructions.

**Comment by jasonrhaas** [comment]
This is up on PyPi now.  `pip install scutils` will install the module.
