### ISSUE TITLE
How to deploy on amazon ECS?

### ISSUE THREAD

**Issue by hustshawn** [istresearch/scrapy-cluster#135]
Is there anyone have the experience on deploy the cluster to ECS?

**Comment by madisonb** [comment]
If by ECS you mean the Amazon [Elastic Container Service](https://aws.amazon.com/ecs/), you are still subject to the AWS [Terms of Service](https://www.amazon.com/gp/help/customer/display.html/?nodeId=508088). The relevant section for web scraping appears to be:

> This license does not include any resale or commercial use of any Amazon Service, or its contents; any collection and use of any product listings, descriptions, or prices; any derivative use of any Amazon Service or its contents; any downloading, copying, or other use of account information for the benefit of any third party; or any use of data mining, robots, or similar data gathering and extraction tools.

Given that this project is based on Scrapy, there are ways you can use http proxies to route your crawl requests out of the AWS infrastructure, but that is best left for a custom implementation for you scrapy cluster setup.

---
However,

**Comment by hustshawn** [comment]
Really understand your concern about aws claim. 

The major problem I met when I deploy the cluster with docker-compose, is the Kafka/Zookeeper will not keep running while kafka-monitor/redis-monitor would depend on them, so the cluster cannot bring up. But the cluster can be up running in my local machine with the same images and same configure(include the networking). That is the reason why I raise the issue. Really expect someone can share some ideas.

**Comment by madisonb** [comment]
Got it, I would look into why the Kafka/Zookeeper containers won't stay running then, but I can leave this question open for now in case you have any updates or for anyone to provide additional feedback.

**Comment by qianlifu12345** [comment]
Have you try to deploy the scrapy cluster on the Kubernates? May be you can try to deploy Kafka/Zookeeper service out of the container cluster.
