### ISSUE TITLE
Utilizing scrapy-cluster to handle high volumes of input URLs

### ISSUE THREAD

**Issue by steveshi7** [istresearch/scrapy-cluster#138]
I'm working with Scrapy Cluster on a project that I'm working on, and one of our particular use cases involves inputting high volumes of URLs into the pipeline to be scraped. To my understanding, Scrapy Cluster is designed to handle seed URLs to be crawled further, rather than an initial input of large URLs. Particularly, the Kafka Monitor seems to handle each input API request one at a time, rather slowly, and is currently the main bottleneck in the pipeline.

Could I have any guidance on whether Scrapy Cluster supports the following features (that would be ideal for our use case), or some guidance on how to modify Scrapy Cluster to support the features?

- Either increasing the speed at which Kafka Monitor handles URLs (or distributing the work), or bypassing Kafka Monitor to directly submit URLs into Redis.

- On the Scraper side, being able to modify the Request meta attributes for seed URLs before the enter the parse() method in order to support custom proxy middleware. (It seems to me like you can only modify the meta attributes for newly crawled links to be added back into the pipeline).

- Is there a way to have throttled priority queues, but also have FIFO on a equal-priority basis? AKA, if I have 50,000 URLs with priority 50, I want to prioritize scraping URLs that were inputted first. Additionally, I see that there are other queues outside of the default throttled priority queue provided. If I were to use any of these queues, or wanted to implement my own, where exactly would I incorporate the new queues? Would I have to rewrite the distributed_scheduler file to work with new queues?

**Comment by steveshi7** [comment]
I noticed that I can decrease the SLEEP_TIME setting for kafka_monitor in order to help with the first bullet point. What's the purpose of the sleep time in the loop, and is there any particular danger to decreasing the sleep_time to say 0?

**Comment by madisonb** [comment]
@steveshi7 All good questions:

• Given that Scrapy Cluster uses Apache Kafka as its data bus, it does not make sense to write directly from Kafka into Redis, you have to have a middleman. Kafka itself can handle really high volumes of data, how many partitions are you running on your inbound topic? You can scale the kafka monitor process to the number of paritions in your topic, and depending on how big your kafka cluster is you you should be able to scale pretty easily to meet your needs

• Custom proxies will definitely work, as long as you add the proper middleware to your spider you should be fine. The only known middleware that doesn't work at this time is stuff to do with Splash, but I hope to finish up that work here soon. You are free to modify the link spider or create your own, with your own middlewares, the link spider and wandering spider are just examples, however I do recommend you keep the current middlewares and just add your own.

• If you can find a Redis data type that supports it, I am sure it would be possible. I don't think Redis has any guarantees about returning data of the [same priority](https://redis.io/commands/zadd#elements-with-the-same-score), but there may be still a way that you can achieve your desired effect. You can increase the default limits of the scores (default is 1-100) and then order everything 50,000 -> 1, and then set your priority [decrease](https://git.io/vdA27) on subsequent crawls to something greater than your whole set (ie 50,001). I have tried to make the distributed scheduler _fairly_ agnostic, however you would need to triple check [here](https://git.io/vdA2x) and [here](https://git.io/vdA2h) to see if it really is that simple to swap the queue class out.

• I would stay away from decreasing the sleep time too much, it will eat CPU when your queue is empty. It's like running a while: True loop with very little or no logic inside.

Overall, my guess is that you do not have a large enough Kafka cluster to support your requests. Scrapy Cluster can scale fairly easily to millions of crawls per day. I would check out the [production setup](https://goo.gl/PSvI4F) docs, and in practice you can easily crawl 1000 pages per minute with just a single machine. 

In a production environment your 50,000 queue of a single domain could be managed in a number of ways
• Dump all of them into kafka as fast as you can, the proper number of partitions in your topic should be large enough to handle the volume and the KM can process it accordingly
• Scale your crawlers wide, obviously this hurts your budget but the more static IP addresses you can get the better. If you use a rotating proxy with a pool of IP's you will get undesired effects, and I would recommend used a single proxy ip assigned to a single machine or container config. Adjust the crawler throttle values to your desire (they are very moderate by default), just dont get yourself banned.
• With a properly tuned cluster, you should never have a large queue in Redis - anything over 100k ends up degrading performance and you should adjust the number of crawlers, speed, or other optimizations (like exporting parsing to another stream processing infrastructure like Apache Storm) to make your spider faster.

----
That's a long winded response to your questions, if that answers then then please close this ticket. If you would like further help or to chat more lets move this conversation over to Gitter, as I would like to leave github issues for formal feature requests or problems, not custom setups.

**Comment by steveshi7** [comment]
Thanks for the help! Just messaged you on Gitter.
