### ISSUE TITLE
exposing kafka from docker

### ISSUE THREAD

**Issue by tycho01** [istresearch/scrapy-cluster#140]
I'm using the Docker setup provided in this repo, and was wondering if anyone has tried to access the scraped data in the dockerized Kafka from outside of the container.

The `docker-compose.yml` file does expose the right ports, yet I couldn't appear to subscribe to topics from outside the container, though from inside this worked well (using the same command).

This seemed like a Kafka + Docker problem, so I googled around, and most answers involved setting the `KAFKA_ADVERTISED_HOST_NAME` environment variable, currently absent from `docker-compose.yml`.

I tried setting that to different values (`127.0.0.1` or `localhost`; `kafka` or `scrapycluster_kafka_1` with an entry in my hosts file to route them to `127.0.0.1`), but any of these would mess up the communication between the different containers for this repo -- to the point where I also wasn't able to verify whether the change had its intended effect.

At this point I'd wonder, has anyone else managed to interface with data scraped using the provided Docker Compose file from outside the container?

Steps to reproduce:
```bash
docker compose up
/opt/kafka/bin/kafka-topics.sh --zookeeper localhost:2181 --list
# ^ ok, works from both inside and from outside container
/opt/kafka/bin/kafka-console-consumer.sh --bootstrap-server 127.0.0.1:9092 --from-beginning --topic demo.incoming
curl 127.0.0.1:5343/feed -H "Content-Type: application/json" -d '{"url":"http
://www.google.com", "appid":"curl", "crawlid":"abc", "allowed_domains":["www.google.com"]}'
# ^ listen to topic and ensure it has messages -- successfully shows message from kafka container, not from host
^C
nano docker-compose.yml
# add environment variable for Kafka: KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
docker compose up
# bunch of errors:
# rest_1           | 2017-10-27 10:28:18,226 [rest-service] ERROR: Couldn't initialize kafka consumer for topic
# kafka_1          | waiting for kafka to be ready
...
# kafka_1          | [2017-10-27 10:28:25,891] WARN Unexpected error from /172.18.0.1; closing connection (org.apache.kafka.common.network.Selector)
# kafka_1          | org.apache.kafka.common.network.InvalidReceiveException: Invalid receive (size = 1195725856 larger than 104857600)
...
# rest_1           | 2017-10-27 10:28:58,742 [rest-service] ERROR: Failed to send message to Kafka
```

**Comment by madisonb** [comment]
@tycho01 

So if you change the kafka advertised hostname I am fairly certain you need to change all of the other containers to point at it as well. I know this has been an ongoing issue with the particular kafka container example setup used in this project, and I would recommend finding your own kafka (docker) solution if you need it exposed on the host and inside of the network.

I don't have any example compose files laying around, however I am fairly certain one of these solutions will work for you.

These are suggestions, hopefully it will get you on the right track to solving it
1) Use the internal docker ip address and expose kafka on that. Something like `172.17.0.1` is typical on most linux setups. You might have success with this in combination with
```
extra_hosts:
    - yourkafkahostnamehere:172.17.0.1
```
for your other containers if you are not using the normal ip.

2) In a similar vein, on the host OS you might have luck configuring the `/etc/hosts` file to reroute stuff on the host to talk to the kafka container. A simple mapping here might suffice

3) I have also had luck with [Traefik](https://docs.traefik.io/), although this is the most complex setup of them all.

Citing your above complaints is why we chose not to run kafka-docker in production, the native install is much friendlier to work with and the docker-containers (and non-docker stuff) can connect just fine. The docker-compose file is an example, and not necessarily the best practice in production for your use case.

**Comment by madisonb** [comment]
I add to this that running kafka in docker is not necessarily this projects goal, but the docker-compose files are provided by example. I would suggest opening a ticket on the kafka-docker repo of your choice and working with the original authors.

Given that this is a custom setup, I would prefer to keep github issues to problem with actual scrapy cluster code, instead of custom configurations. Please close this ticket and I am happy to chat further on gitter.

**Comment by tycho01** [comment]
Thanks for the ideas! I realize this may have been largely out of scope here, so I appreciate the hints.
Skipping out on Docker so as to cut down on these port/host concerns definitely makes sense there. I'll experiment a bit more then!

**Comment by gsunjka** [comment]
@tycho01 

I had the same issue. After adding my host ip address to KAFKA_ADVERTISED_HOST_NAME everything worked fine.

**Comment by User1m** [comment]
thanks @gsunjka this helped solve my issue.
in case you need to find the host ip address from dockers point run [`/sbin/ip route|awk '/default/ { print $3 }'`](https://stackoverflow.com/a/38776146/3562407) inside a container
