### ISSUE TITLE
Persistent DNS cache

### ISSUE THREAD

**Issue by codywilbourn** [istresearch/scrapy-cluster#15]
One of the sites we are crawling has alerted us to an issue where we were hitting a load balancer with a 1h TTL record over a week after they changed the DNS.

It appears that the default operation for Scrapy is to use a [in-memory DNS cache](http://doc.scrapy.org/en/1.0/topics/settings.html#dnscache-enabled), which apparently [never gets flushed](https://github.com/scrapy/scrapy/issues/905). Since the spiders are long running, you run into the reported issue.

I'm going to try setting `DNSCACHE_ENABLED` to `False` in my settings and see if that improves things. If it does, we should set that in settings.py so no one else runs into this problem.

**Comment by codywilbourn** [comment]
As an ops-y note, some server operating systems do not have local DNS caches by default. If we do change `settings.py` to disable DNS cache, there should be a note in the documentation about possibly needing to configure a DNS cache if the user finds the DNS request volume too much.

**Comment by madisonb** [comment]
Sounds good - that is a good edge case to catch as we have not seen that in production. Happy to accept a pull request into the main `dev` branch or make the settings change myself when I hear back that it worked. 

If it is `master` branch hotfix worthy the same applies.

**Comment by madisonb** [comment]
Merged and docs updated, commit 1f7246dee7a559210eaf9fde34f2ba4caf6b73e8 and e6b0ecb41894b89312d5a47922b9a507e195fea0.
