### ISSUE TITLE
Docker Quickstart Error for Crawler container

### ISSUE THREAD

**Issue by edolix** [istresearch/scrapy-cluster#162]
Hi guys,
Thanks for this amazing project!

I've some trouble setting up a dockerized cluster. 
I am following [this quickstart](http://scrapy-cluster.readthedocs.io/en/latest/topics/introduction/quickstart.html#docker-quickstart) step by step but  - only into `scrapycluster_crawler_1`  - the online test does not pass properly.

My local setup:

```
MacBook Pro - High Sierra
Docker4Mac Version 17.12.0-ce-mac47 (21805)
```

Below full console output:

```
root@e5bea50cbe71:/usr/src/app# ./run_docker_tests.sh
/usr/src/app/crawling/distributed_scheduler.py:8: ScrapyDeprecationWarning: Module `scrapy.conf` is deprecated, use `crawler.settings` attribute instead
  from scrapy.conf import settings
test_change_config (test_distributed_scheduler.TestDistributedSchedulerChangeConfig) ... ok
test_create_queues (test_distributed_scheduler.TestDistributedSchedulerCreateQueues) ... ok
test_enqueue_request (test_distributed_scheduler.TestDistributedSchedulerEnqueueRequest) ... /usr/local/lib/python2.7/site-packages/requests/packages/urllib3/connection.py:306: SystemTimeWarning: System time is way off (before 2016-01-01). This will probably lead to SSL verification errors
  SystemTimeWarning
ok
test_error_config (test_distributed_scheduler.TestDistributedSchedulerErrorConfig) ... ok
test_expire_queues (test_distributed_scheduler.TestDistributedSchedulerExpireQueues) ... ok
test_find_item (test_distributed_scheduler.TestDistributedSchedulerFindItem) ... ok
test_fit_scale (test_distributed_scheduler.TestDistributedSchedulerFitScale) ... ok
test_load_domain_config (test_distributed_scheduler.TestDistributedSchedulerLoadDomainConfig) ... ok
test_next_request (test_distributed_scheduler.TestDistributedSchedulerNextRequest) ... ok
test_parse_cookie (test_distributed_scheduler.TestDistributedSchedulerParseCookie) ... ok
test_update_domain_queues (test_distributed_scheduler.TestDistributedSchedulerUpdateDomainQueues) ... ok
test_link_spider_parse (test_link_spider.TestLinkSpider) ... ok
/usr/src/app/crawling/log_retry_middleware.py:10: ScrapyDeprecationWarning: Importing from scrapy.xlib.tx is deprecated and will no longer be supported in future Scrapy versions. Update your code to import from twisted proper.
  from scrapy.xlib.tx import ResponseFailed
test_lrm_stats_setup (test_log_retry_middleware.TestLogRetryMiddlewareStats) ... ok
test_mpm_middleware (test_meta_passthrough_middleware.TestMetaPassthroughMiddleware) ... ok
test_process_item (test_pipelines.TestKafkaPipeline) ... ok
test_process_item (test_pipelines.TestLoggingBeforePipeline) ... ok
test_dupe_filter (test_redis_dupefilter.TestRedisDupefilter) ... ok
test_retries (test_redis_retry_middleware.TestRedisRetryMiddleware) ... ok
test_load_stats_codes (test_redis_stats_middleware.TestRedisStatsMiddleware) ... ok
test_rsm_input (test_redis_stats_middleware.TestRedisStatsMiddleware) ... ok
test_link_spider_parse (test_wandering_spider.TestWanderingSpider) ... ok

----------------------------------------------------------------------
Ran 21 tests in 4.665s

OK
/usr/src/app/crawling/spiders/link_spider.py:6: ScrapyDeprecationWarning: Module `scrapy.conf` is deprecated, use `crawler.settings` attribute instead
  from scrapy.conf import settings
test_crawler_process (__main__.TestLinkSpider) ... /usr/src/app/crawling/log_retry_middleware.py:10: ScrapyDeprecationWarning: Importing from scrapy.xlib.tx is deprecated and will no longer be supported in future Scrapy versions. Update your code to import from twisted proper.
  from scrapy.xlib.tx import ResponseFailed
2018-01-16 22:30:13,058 [sc-crawler] INFO: Changed Public IP: None -> b'87.4.65.220'
ERROR

======================================================================
ERROR: test_crawler_process (__main__.TestLinkSpider)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/online.py", line 92, in test_crawler_process
    m = next(self.consumer)
  File "/usr/local/lib/python2.7/site-packages/future/builtins/newnext.py", line 65, in newnext
    raise e
StopIteration

----------------------------------------------------------------------
Ran 1 test in 36.955s

FAILED (errors=1)
integration tests failed
```

Thanks!

**Comment by madisonb** [comment]
This was brought up on Gitter recently, can I ask if you are actually running all the docker containers in the docker-compose file? Otherwise, this issue brought up identified that [this](https://goo.gl/inAqcA) line should be changed to reflect `"spiderid": "test-link"` instead of `"spiderid":"link"` and that fixed that person's issue.

Otherwise, the online integration tests are meant as a way for you to troubleshoot your cluster to see if you have everything configured correctly, perhaps one of your containers is not starting properly?

**Comment by edolix** [comment]
@madisonb thanks for reply. 
I'm running properly all containers (`docker-compose up -d` from the root dir) and all containers seem fine.

I changed `link ` with `test-link` on [this line](https://github.com/istresearch/scrapy-cluster/blob/master/crawler/tests/online.py#L41) but it didn't work. 

Reading code i also tried with `test-spider` [this other line](https://github.com/istresearch/scrapy-cluster/blob/master/crawler/tests/online.py#L32) but get same result. 

I'm using branch master and delete/re-create containers on every tests.

**Comment by madisonb** [comment]
There are two different elements you can try.

1) Set the Scrapy Logger level to `DEBUG` -> this will dump logs into the main container logs

2) Set the Scrapy Cluster Logger level to `DEBUG` - this will dump logs where ever you configure it to point, I would suggest stdout but you can write to a file as well.

From there you should be able to run the integration test. However, you can also skip down to [Your First Crawl](https://scrapy-cluster.readthedocs.io/en/latest/topics/introduction/quickstart.html#your-first-crawl) and try to run the commands from there: In your case, you would exec 2 sessions into the kafka monitor container, one to execute the command to crawl, and the other to tail the kafka output. 

If this also fails, I would suggest further troubleshooting the kafka container, and looking at the logs. Tail the logs on the kafka container, it may be throwing an error/warning that would indicate the container is not healthy, even though `docker ps` says it is "up".

**Comment by madisonb** [comment]
Please use the new 1.2.1 containers -> they have passed all their integration tests and have been pushed to dockerhub. (note that the integration tests on Travis [1](https://github.com/istresearch/scrapy-cluster/blob/master/travis/docker.sh#L17-L21) and [2](https://travis-ci.org/istresearch/scrapy-cluster/jobs/330870105) are the same as in the quickstart).

Closing.

**Comment by edolix** [comment]
Thanks @madisonb !!
