### ISSUE TITLE
Is there a way to get dynamic url or other tag links?

### ISSUE THREAD

**Issue by bipabo1l** [istresearch/scrapy-cluster#164]
In the crawler's result, I only saw the URLs of  tag <a>. I did not find the URLs of other tags, such as <iframes>, form forms, or links in javascript. I want to get these links. Currently, I only run crawler / crawling / link_spider.py. Is there any other way to implement my needs? Thanks

**Comment by madisonb** [comment]
This sounds like a Scrapy issue, you are free to modify the generic spider and pipeline in this project to suit your needs. Can I close this?

**Comment by bipabo1l** [comment]
Yes
