### ISSUE TITLE
What is Kafka's role in scrapy-cluster?

### ISSUE THREAD

**Issue by crisfan** [istresearch/scrapy-cluster#172]
hi,madisonb! it's an amazing project,Thank you for your contribution.

Here's some questions that have been bothering me for a long time.
1. Why build kafka between rest and kafka-monitor?What problem does it want to solve?
2. If the data from rest output is small, can we deliver it directly to kafka-monitor?

After I looked up the information on kafka,I think it's just a buffer in this project, right?
hope to receive your reply，thanks!

**Comment by madisonb** [comment]
1. The Rest interface allows the kafka monitor to handle the cluster's API validation calls. Building the same code into the restful interface would mean repeating lots of code across both projects. See the docs [here](https://scrapy-cluster.readthedocs.io/en/latest/topics/rest/design.html) for more information
2. I would take a look at the architecture diagram on [this](https://scrapy-cluster.readthedocs.io/en/latest/topics/introduction/overview.html) page to see how everything interacts. The restful component is meant to be consumed by something more UI friendly. The kafka monitor still has its place too.

Kafka is indeed used as the message bus throughout this project.

Given that these are general questions and not issues with the project, can I close this and we can move further conversation to Gitter? Thanks.

**Comment by crisfan** [comment]
Looking forward to talking to you on gitter！
