### ISSUE TITLE
Inter-spider communication

### ISSUE THREAD

**Issue by shenbakeshkishore** [istresearch/scrapy-cluster#178]
Hi,

Please share sample code to perform inter-spider communication.(In reference to https://scrapy-cluster.readthedocs.io/en/latest/topics/crawler/controlling.html#inter-spider-communication)

**Comment by madisonb** [comment]
If you read that section it gives you an example, but here is a more complete one:

```
req = Request(some_url, callback=self.parse)
req.meta['spiderid'] = 'myotherspidername'
yield req
```

Closing.
