### ISSUE TITLE
Typo on document of Kafka-monitor API section

### ISSUE THREAD

**Issue by chihkaiyu** [istresearch/scrapy-cluster#183]
Hi all,
I'd found a typo on [this page](http://scrapy-cluster.readthedocs.io/en/latest/topics/kafka-monitor/api.html): `demo.crawled_firehouse`.
It should be `demo.crawled_firehose` and I think it's just a typo.
I was stuck for a while and kept diving into the code to see if I did something wrong lol
Maybe we should add a warning (or an exception) here if someone tries to dump the result from a non-exist Kafka topic.
Not just create a topic and keep dumping the result from it but this is not the issue we want to discuss here.
Here is the related PR: https://github.com/istresearch/scrapy-cluster/pull/184

**Comment by madisonb** [comment]
Good catch, I am impressed that typo lasted as long as it did. Fixing right now... Ah I see you already made a PR -> I will resolve it here soon.

**Comment by madisonb** [comment]
PR Merged, closing.
