### ISSUE TITLE
Docker vs Vagrant

### ISSUE THREAD

**Issue by mshahriarinia** [istresearch/scrapy-cluster#192]
I had a question if you may,

Why is this based on vagrant as opposed to docker? Docker seems to make more sense given that instances are fairly simple and don't need a whole OS.

**Comment by madisonb** [comment]
Docker is fully supported by this project
* [Quickstart](https://scrapy-cluster.readthedocs.io/en/latest/topics/introduction/quickstart.html#docker-quickstart)
* [Advanced docker usage](https://scrapy-cluster.readthedocs.io/en/latest/topics/advanced/docker.html)
* [Dockerhub](https://hub.docker.com/r/istresearch/scrapy-cluster/tags/)

Closing.
