### ISSUE TITLE
tests_offline.py path dependency issue

### ISSUE THREAD

**Issue by jasonrhaas** [istresearch/scrapy-cluster#20]
When running the `tests_offline.py` manually using `python tests_offline.py`, it will fail unless it is run from the **utils** directory.  The `run_offline_test.sh` works because it changes to the **utils** folder before running.

This can be solved by using the current directory instead of using "test" in the code.

Lines 167, 168:
```
                dir='test', level='INFO', stdout=False, file='test.log')
        self.test_file = 'test/test'
```

can be changed to:
```
                dir='.', level='INFO', stdout=False, file='test.log')
        self.test_file = './test'
```

and the test will work from any directory.

**Comment by madisonb** [comment]
Technically the docs for all the testing are going to explicitly state "run from the main directory like so: `python tests/tests_offline.py -v`" so while this is helpful it probably affects more than just the utils, but we can make a separate issue for that if needed.
