### ISSUE TITLE
Replace Kafka with another pub/sub service?

### ISSUE THREAD

**Issue by jrmlhermitte** [istresearch/scrapy-cluster#215]
I'm just curious how hard it would be to replace kafka with another messaging service, say RabbitMQ, google pub sub, or something else.
Are there plans to do this?

**Comment by madisonb** [comment]
There are no plans to do this at this time, however I have certainly thought about adding additional support for other queue frameworks.

You would need to touch every major component, however you would simply need to swap out the code for "reading data from the queue" and "pushing data to the queue".

I am not super familiar with the best practices with RabbitMQ or Redis/Google PubSub, so for now I think I am going to leave it as is.

**Comment by madisonb** [comment]
Closing this ticket

**Comment by jrmlhermitte** [comment]
sounds good thanks for the info
