### ISSUE TITLE
Plans to support latest version of Kafka, ELK & Scrapy?

### ISSUE THREAD

**Issue by kumaresra** [istresearch/scrapy-cluster#217]
Any plans to support the latest version of Kafka, ELK & Scrapy?

**Comment by madisonb** [comment]
I bump things most of the time when it is needed or I get a PR for it.

Current versions in this project under the `dev` branch
`Scrapy==1.5.0`

[Tested](https://travis-ci.org/istresearch/scrapy-cluster/builds/536397186) against [containers](https://github.com/istresearch/scrapy-cluster/blob/master/travis/docker-compose.test.yml#L31-L42)
`wurstmeister/kafka` (latest)
`wurstmeister/zookeeper` (latest)
`redis` (latest)

In terms of ELK - this project is not meant to be bleeding edge against the ELK stack, the example in the documentation and located within this codebase is meant to be just an example. However, the logstash config I know works up through the 6.x series, and I am sure would be easy enough to get working against the latest 7.x series. That primary logging interface within Logstash doesn't change much.

If this answers your question, please close this ticket
