### ISSUE TITLE
Docker ERROR: Could not ping Zookeeper

### ISSUE THREAD

**Issue by Shique** [istresearch/scrapy-cluster#220]
There seems to be an issue both on the `dev` and `master` branches - the crawler container keeps failing and restarting with the following message:

> ERROR: Could not ping Zookeeper

I've tried this with a fresh copy of the crawler on both Windows and MacOS with the same result.

To replicate - download either branch and issue the command:
```bash
docker-compose up -d
```

**Comment by Deadly0** [comment]
@Shique Try image `wurstmeister/zookeeper`. it's works for me

**Comment by madisonb** [comment]
The wurstmeister image is definitely preferred, not sure why I had it at the default dockerhub zookeeper image, but will change both branches to fix that.

**Comment by madisonb** [comment]
Fixed on both branches, `docker-compose up -d` is working.

**Comment by softwarevamp** [comment]
zookeeper:3.4 works, zookeeper:3.5+ fails.

**Comment by softwarevamp** [comment]
zookeeper:3.5+ returns
`envi is not executed because it is not in the whitelist.`

**Comment by softwarevamp** [comment]
`-e ZOO_4LW_COMMANDS_WHITELIST="*"` fix this.
