### ISSUE TITLE
Cannot turn off DEBUG level log

### ISSUE THREAD

**Issue by YanzhongSu** [istresearch/scrapy-cluster#223]
In Scrapy cluster, I have the following log settings: `SC_LOG_LEVEL=INFO`, `SC_LOG_STDOUT=False`

But for some reason, I still get DEBUG level log being printed out in the console. Here is the sample log
`[scrapy.core.engine] DEBUG: Crawled (200) <GET https://www.google.com>`
`[sc-crawler] INFO: crawled processed successfully`
`[scrapy.core.scraper] DEBUG: Scraped from <200 https://www.google.com>`

Does anyone how to turn it off?

**Comment by madisonb** [comment]
Scrapy Cluster's logger is not the same as Scrapy's logger, they are two different things. If you would like to change Scrapy's logger, use the setting `LOG_LEVEL` as outlined [here](http://doc.scrapy.org/en/latest/topics/logging.html#logging-settings). 

If you would like you adjust the Scrapy Cluster project's logger, you can do that with the log prefixes that are `SC_*` (so they do not conflict) as found [here](https://scrapy-cluster.readthedocs.io/en/latest/topics/crawler/settings.html#logging).

If this resolves your issue please close the ticket.

**Comment by YanzhongSu** [comment]
Thank you @madisonb . It worked.
