### ISSUE TITLE
A mistake in parameter deliver through two method!

### ISSUE THREAD

**Issue by kevin-ZZZ** [istresearch/scrapy-cluster#225]
Hey,madisonb:
        I found a problem  in parameter delivering! I  instantiate an item object in method A,and then deliver it through meta.but I got a list object in method B,not the same item object ! 

```
def parse(self,response):
    item = item_object()
    item["xx"] = "xxx"
    yield scrapy.Request(url, meta={"item": item}, callback=self.parse_images)

def parse_image(self,response):
    item = response.meta["item"]
```
The type of item will be  list,not a item object!

 However ,when I used a dict object as parameter to deliver through different method,I could get the same dict like this:
```
def parse(self,response):
    item = item_object()
    item["xx"] = "xxx"
    yield scrapy.Request(url, meta={"item": dict(item)}, callback=self.parse_images)

def parse_image(self,response):
    item = dict(response.meta["item"][0])
```

And I can get a dict object!
Is this a bug or just a mistake?
Thanks for help!

**Comment by madisonb** [comment]
What branch are you on? Can you replicate this behavior in the `dev` branch too? We changed how the request serialization works and now use the internal Scrapy serializer, so I would be curious if you can replicate it there.

**Comment by kevin-ZZZ** [comment]
@madisonb    I was on dev branch,I used python3.6, but the code was cloned half year ago,So I'm curious when you solve the problem ,All I need do is just need update the code? And it will be nice to show me the git version about this problem?

**Comment by madisonb** [comment]
Did you ever figure this out? Otherwise I am going to close the issue due to inactivity

**Comment by madisonb** [comment]
Closing.
