### ISSUE TITLE
Crawler unhandled exceptions not logged

### ISSUE THREAD

**Issue by getorca** [istresearch/scrapy-cluster#259]
With only LOG_ENABLED = false in settings.py , default behaviour, when running with docker compose you loose logging of unhanded exceptions such as `KeyError`s. This is in the crawler service.

expected behaviour: unhanded exceptions get logged

It might make sense to have:
```
LOG_ENABLED = str2bool(os.getenv('LOG_ENABLED', True))
LOG_LEVEL = os.getenv('LOG_LEVEL', 'ERROR')
```

as the default so that unhandled exceptions are still logged and visible.

**Comment by madisonb** [comment]
This is a Scrapy [setting](https://docs.scrapy.org/en/latest/topics/settings.html#log-enabled), not a Scrapy Cluster setting. This project has no control over what that setting does or how it impacts scrapy logging.

Closing.
