### ISSUE TITLE
Status

### ISSUE THREAD

**Issue by quasiben** [istresearch/scrapy-cluster#27]
Noticed `master` hadn't had an update in quite some time.  Is this project currently still underdevelopment ?

**Comment by madisonb** [comment]
Check out the `dev` branch! There is a large amount of documentation that needs to occur with all the work that has been done (for 1.1), but hopefully you can figure everything out and if you have any questions let us know. It will be merged back into the `master` branch when everything has been thoroughly tested, scaled, and documented.

You can also use the 1.1 Milestone issue filter to look at commits and chatter about the things we are adding.

If that answers your question please close this issue.

**Comment by quasiben** [comment]
Ah, missed the dev branch. Thanks!
