### ISSUE TITLE
Feeding speed is slow, how to speed up?

### ISSUE THREAD

**Issue by rocdeng** [istresearch/scrapy-cluster#33]
Great job and thanks a lot, this project is the only one which on github could work correctly.

And I've met one problem: the feeding speed is slow, I have push more than 100000 records to queue, and it's really a nightmare, is there any way to speed it up?

**Comment by madisonb** [comment]
If you are using the `dev` branch (almost official SC 1.1) the crawlers are purposefully throttled so you do not get yourself banned. You can speed up your crawlers by altering the Scrapy settings.py file or overriding them in your localsettings.py file, and then restarting all instances of your scrapy spiders.

The following lines tell the crawlers to run at X HITS per domain in Y seconds (https://github.com/istresearch/scrapy-cluster/blob/dev/crawler/crawling/settings.py#L43-#L44). Alter them and restart your spiders, but be warned if you hit a particular domain too fast your IP may get temporarily banned and is out of our control. 

By default they allow 10 hits in 60 seconds, which is pretty light weight. I would suggest either increasing the number of outbound IP addresses you have (so now you crawl at 10 hits per minute x # of IP's you have), or increasing the allotted number of hits in the timeframe for a single IP address.

For most sites, 60 hits in 60 seconds (1 hit per second) will get the job done with minimal 403's or 404's for the domain.

**Comment by rocdeng** [comment]
Oh, it a misunderstanding... I don't mean the grabbing speed. I mean when I pushed the job to the queue using "kafka-monitor.py feed '{"url": "xxxxx", "appid":"testapp",xxx" command, the speed is slow :)

**Comment by rocdeng** [comment]
And btw: I checkouted the dev branch, but found it's different like the master. For example, the command "python kafka-monitor.py run -s settings_crawling.py" and "python kafka-monitor.py feed -s settings_crawling.py '{"url": "http://istresearch.com", "appid":"testapp", "crawlid":"ABC123"}'"  are not working, I've tried "python kafka_monitor.py run -s settings.py" but still not work, the docs are still for old ones, any tips?

**Comment by madisonb** [comment]
We can't really speed up the 'feed' command as the main bottleneck is setting up the Kafka connection and writing the data. In a production setup you should write your own application to leave the Kafka connection open and write data into it continuously.

I would use the `-h` flag on any command if you are having trouble figuring out how it works. You can also look at the 1.1 [quickstart](http://scrapy-cluster.readthedocs.org/en/1.1-docs/topics/introduction/quickstart.html) guide to see how things work. Note that all those 1.1 docs are not done but that page is.

**Comment by rocdeng** [comment]
OK thanks a lot. And I wrote a multi-thread feeding program, the speed is much more faster :)

**Comment by madisonb** [comment]
Sounds great. If this satisfies your original question for raising this issue, can you please close it out?

**Comment by rocdeng** [comment]
Sure, thanks a again and can't wait to see the 1.1 release!
