### ISSUE TITLE
Zookeeper dependency?

### ISSUE THREAD

**Issue by sibiryakov** [istresearch/scrapy-cluster#37]
Hey guys!

We've met at Memex Summer workshop last time. I was looking through this code, and didn't found any dependency on Zookeeper. Am I missed something? If not, probably it makes sense to remove it from docs.

**Comment by madisonb** [comment]
Zookeeper is a dependency for Kafka, and for controlling the crawlers in version 1.1. So your Kafka hosts needs to connect to ZK as well as all of your Scrapers (if you chose to work off of the `dev` branch)

**Comment by madisonb** [comment]
If you have any further questions about the Zookeeper dependency please reopen this issue, otherwise closing for now.
