### ISSUE TITLE
Can the spiders not exit after all the job done? #question

### ISSUE THREAD

**Issue by rocdeng** [istresearch/scrapy-cluster#38]
Hi, Can the spiders not exit after all the job done and waiting for new job?
I remember scrapy has this function, but I don't know how to modify the settings or code to make scrapy-cluster like that.
Thanks for reply.

**Comment by madisonb** [comment]
Both the link spider and the wandering spider provided in scrapy cluster 1.1 do not exit when the job ends. If you inherit from the base `RedisSpider` class your spiders will not exit and continue to stay in the cluster.

For more information please see http://scrapy-cluster.readthedocs.org/en/1.1-docs/topics/crawler/extension.html

**Comment by rocdeng** [comment]
Thanks and I'll take a look at the v1.1 spider :+1:
