### ISSUE TITLE
Switch from Kafka-Python to PyKafka

### ISSUE THREAD

**Issue by madisonb** [istresearch/scrapy-cluster#42]
PyKafka (https://github.com/Parsely/pykafka) supports consumer groups and will allow us to scale the Kafka Monitor horizontally so there is not a single point of failure on the API incoming requests.

This should apply to everything using Kafka Python, so crawlers and redis monitor too. Ultimately we want to remove the `kafka-python` dependency.

**Comment by madisonb** [comment]
Under this release of Kafka-Python (https://github.com/dpkp/kafka-python/releases/tag/1.0.0), apparently support for consumer groups works for kafka 0.9 and above. PyKafka supports consumer groups backwards through 0.8, so it now a choice on what Scrapy Cluster should support. 

This requires significantly less code modification than migrating to a new package.

**Comment by amontalenti** [comment]
0.9 support for pykafka is being tracked in this PR, which is active:

https://github.com/Parsely/pykafka/pull/416

pykafka will support 0.8.2 and 0.9.x in a single codebase, where for the former you'd use zookeeper for offsets and in the latter you'd use Kafka's in-built facilities.

**Comment by madisonb** [comment]
Thanks @amontalenti! That PR is slated for pykafka `2.3.0` which appears to be the next release save for a minor 2.2.x release. I think I can delay working on this until you guys merge it in and then we can make a decision on how much code needs to be refactored for upgrading to either new implementation.

**Comment by madisonb** [comment]
As of right now, upgrading to the latest `kafka-python` was the easiest route. Closing.
