### ISSUE TITLE
Production ready ?

### ISSUE THREAD

**Issue by PradeepJaiswar** [istresearch/scrapy-cluster#68]
I am up to setting up my own cluster for scrapping using individual components such as
- Supervisor
- Scrapy
- Kafka for msg
- Celery for queue and Rebbitmq/redis as broker
- Flask for rest
- Etc

And I'm trying to stitch all this above parts together and make my crawling system. Came across this repo and specs looks awesome. 

- Zookeeper
- Kafka
- Redis
- Crawler(s) Scrapy
- Kafka Monitor
- Redis Monitor

And by reading document i must admin every component seems to be stitch together nicely.

The problem is that document seems promising but after searching online could not find anyone using it for real-world applications. My question is very simple " is it really production ready ? "

Anyone who is using this on production or thought of using can help me with comment. I know this question is very opinionated but any advice would help. 

I thought this is most appropriate place to ask this question as i could not find anywhere else peple using it. In case if this sounds inappropriate here feel free to close this. 

Do help

**Comment by madisonb** [comment]
Here at IST Research we use Scrapy Cluster to crawl millions of web pages per day. There are many resources to help you learn about Kafka, Zookeeper, Redis, etc so I would recommend getting familiar with the technologies first before trying to stitch then all together. Learning all the technologies while at the same time trying to ensure your cluster is stable and working is a tough.

While this technology is fairly new we have been using it for over 2 years at this point, and would love to continue to support the community with a large scale web crawling framework.

For more informal questions feel free also to reach out in the Gitter chat room as well.

**Comment by madisonb** [comment]
Closing since this is not a direct issue with the codebase.
