### ISSUE TITLE
kafka/zookeeper install failed

### ISSUE THREAD

**Issue by zedzhou** [istresearch/scrapy-cluster#70]
when vagrant up, got following downloads failed. And I have checked apache.arvixe.com and found it is down. if it could be installed into vm for the components which encount network failure?
`
TASK [kafka : download kafka] **************************************************
fatal: [scdev]: FAILED! => {"changed": false, "dest": "/tmp/kafka_2.11-0.9.0.0.tgz", "failed": true, "msg": "Request failed", "response": "Request failed: <urlopen error [Errno 101] Network is unreachable>", "state": "absent", "status_code": -1, "url": "http://apache.arvixe.com/kafka/0.9.0.0/kafka_2.11-0.9.0.0.tgz"}
`

`
TASK [zookeeper : download zookeeper] ******************************************
fatal: [scdev]: FAILED! => {"changed": false, "dest": "/tmp/zookeeper-3.4.6.tgz", "failed": true, "msg": "Request failed", "response": "Request failed: <urlopen error [Errno 101] Network is unreachable>", "state": "absent", "status_code": -1, "url": "http://apache.arvixe.com/zookeeper/zookeeper-3.4.6/zookeeper-3.4.6.tar.gz"}
`

**Comment by madisonb** [comment]
Can you specify what branch you are running from? I dont see `http://apache.arvixe.com` in the zookeeper source or kafka source in either the `dev` or `master` branch. It may have been included in the tagged 1.1 release but there have been minor updates to fix those mirrors that went down, see a9ef7fbc2da34879d2ba143d86509eb47745bba5

**Comment by zedzhou** [comment]
i'm using the commit of [a8b611c](https://github.com/istresearch/scrapy-cluster/commit/a8b611c0759538ba6e38c488b96b64d18ff7be1a) and download the source from the [lastest release](https://github.com/istresearch/scrapy-cluster/releases/tag/v1.1)

**Comment by madisonb** [comment]
I would advise you to pull down the latest master branch and work from there. while the latest tagged release is good there have been small enough changes (like documentation or ansible fixes) that dont warrant a new tagged release.
