### ISSUE TITLE
docker settings.py : env variable naming + incorrect [] array bracket for KAFKA_HOST

### ISSUE THREAD

**Issue by Paw2Pom** [istresearch/scrapy-cluster#75]
=======
Issue 01
=======

For consistency, in the settings.py provided in the docker folders (crawler, kafka-monitor, redis-monitor), the env variable naming for KAFKA_HOST in the os.getenv input, i.e.:

KAFKA_HOSTS = [os.getenv('KAFKA_HOST', 'kafka:9092')]

should be: KAFKA_HOST -> KAFKA_HOSTS

=======
Issue 02
=======
For the same line, the array bracket [] should be removed, otherwise when you set "KAFKA_HOST: kafka1:9092,kafka2:9092" in docker-compose, it will not be able to connect to multiple kafka instances.

=======
Overall
=======
Current: 
KAFKA_HOSTS = [os.getenv('KAFKA_HOST', 'kafka:9092')]
Change to: 
KAFKA_HOSTS = os.getenv('KAFKA_HOSTS', 'kafka:9092')

**Comment by madisonb** [comment]
Issue 1: I think this actually ties in with issue 2 below, as I think I purposely used the singular 'host'.

Issue 2: According to the Kafka Python docs [here](http://kafka-python.readthedocs.io/en/master/apidoc/KafkaConsumer.html#kafkaconsumer), you cannot use a comma separated string of hosts as your `bootstrap_servers`. Instead, you either need a string like `host:port` or a list of strings like `['host1:port1', 'host2:port2', ...]`. I haven't run into the need for this as I have been spinning up Kafka via Docker, but I agree that on production systems you may not want to run Kafka in a docker container.

My solution is pretty simple:
```
KAFKA_HOSTS = [x.strip() for x in os.getenv('KAFKA_HOSTS', 'kafka:9092').split(',')]
```
and I would like to apply it to both the Zookeeper and Kafka based environment variables.

In testing, it results in the following:
```
$ KAFKA_HOSTS='k1:p1, k2:p2, k3:p3' python
Python 2.7.10 (default, Oct  5 2015, 18:27:21)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> [x.strip() for x in os.getenv('KAFKA_HOSTS', 'kafka:9092').split(',')]
['k1:p1', 'k2:p2', 'k3:p3']
>>> [x.strip() for x in os.getenv('KAFKA_HOSTSBLAHBLAH', 'kafka:9092').split(',')]
['kafka:9092']
```
I think this is the best solution, do you agree? I will correct this early next week.

**Comment by Paw2Pom** [comment]
Yap, agree this is best solution! Thanks Madison!

**Comment by Paw2Pom** [comment]
I have done some tests with the following docker-compose env setup for our kafka-monitor, redis-monitor and crawlers:

KAFKA_HOSTS: kafka1:9092,kafka2:9092
ZOOKEEPER_HOSTS: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181

If I use the following correction in the settings.py, everything will work fine:

KAFKA_HOSTS = [x.strip() for x in os.getenv('KAFKA_HOSTS', 'kafka:9092').split(',')]
ZOOKEEPER_HOSTS = os.getenv('ZOOKEEPER_HOSTS', 'zookeeper:2181')

However, if I use the following, all crawlers containers will fail due to connection error with zookeepers:

KAFKA_HOSTS = [x.strip() for x in os.getenv('KAFKA_HOSTS', 'kafka:9092').split(',')]
# ZOOKEEPER_HOSTS = [x.strip() for x in os.getenv('ZOOKEEPER_HOSTS', 'zookeeper:2181').split(',')]

**Comment by madisonb** [comment]
I made that comment without peeking into the `kazoo` documentation [here](http://kazoo.readthedocs.io/en/latest/api/client.html#kazoo.client.KazooClient). I looks like it will accept a comma separated list of hosts as a single string. It turns out that the line:
```
ZOOKEEPER_HOSTS = os.getenv('ZOOKEEPER_HOSTS', 'zookeeper:2181')
```
was actually correct as I wrote it. Sorry for the confusion.

**Comment by Paw2Pom** [comment]
Awesome, thanks Madison!
