### ISSUE TITLE
dockerized sc : "python kafkadump.py dump -t demo.crawled_<appid>" does not dump out the scraped site

### ISSUE THREAD

**Issue by Paw2Pom** [istresearch/scrapy-cluster#77]
Using the "dev" branch:

1. cd elk
2. docker-compose -f docker-compose.elk.yml up
3. docker exec -it elk_kafka_monitor_1 bash
4. python kafka_monitor.py feed '{"url":"cnn.com", "appid":"test","crawlid":"abc1234","maxdepth":2}'
5. python kafkadump.py list
6. python kafkadump.py dump -t demo.crawled_test

Problems encountered:

1. No topic of "demo.crawled_<appid>" can be found.
2. python dump of "python kafkadump.py dump -t demo.crawled_test" has no output

**Comment by madisonb** [comment]
Please see the `KAFKA_APPID_TOPICS` setting [here](http://scrapy-cluster.readthedocs.io/en/dev/topics/crawler/settings.html). Use the `demo.crawled_firehose` as described in the [quickstart](http://scrapy-cluster.readthedocs.io/en/dev/topics/crawler/quickstart.html).

**Comment by Paw2Pom** [comment]
Apology, i just looked through the doc again. Yes it works now! Thank you Madison!
