### ISSUE TITLE
Trouble when adding a new spider

### ISSUE THREAD

**Issue by casertap** [istresearch/scrapy-cluster#78]
Hi, thanks a lot for this project, it is great.
Nevertheless I have a lot of trouble getting my head around all this complex stack.

I can run all the example from the quick start but I want to do more and I want to learn more about the internal of scrapy-cluster.

First of all, I would like to add my own spider, I will start with a very basic one:

````
class BasicSpider(RedisSpider):
    name = "manual"

    def __init__(self, *args, **kwargs):
        super(BasicSpider, self).__init__(*args, **kwargs)

    def parse(self, response):
        # Get the next index URLs and yield Requests
        print response
        next_selector = response.xpath('//*[contains(@class,"next")]//@href')
        for url in next_selector.extract():
            yield Request(urlparse.urljoin(response.url, url))

        # Get item URLs and yield Requests
        item_selector = response.xpath('//*[@itemprop="url"]/@href')
        for url in item_selector.extract():
            yield Request(urlparse.urljoin(response.url, url),
                          callback=self.parse_item)

    def parse_item(self, response):
     ....
````
When I run the command (I am using a local a website that is running on localhost for test purpose)
````
(sc) vagrant@scdev:/vagrant/kafka-monitor$ python kafka_monitor.py feed '{"url": "http://localhost:9312/properties/index_00000.html", "appid":"testapp1", "crawlid":"abc123", "spiderid":"manual"}'
2016-09-18 05:58:00,448 [kafka-monitor] DEBUG: Logging to stdout
2016-09-18 05:58:00,450 [kafka-monitor] INFO: Feeding JSON into demo.incoming
{
    "url": "http://localhost:9312/properties/index_00000.html",
    "spiderid": "manual",
    "crawlid": "abc123",
    "appid": "testapp1"
}
No handlers could be found for logger "kafka.producer"
2016-09-18 05:58:00,453 [kafka-monitor] INFO: Successfully fed item to Kafka
````
I have the kafka-monitor saying
````
2016-09-18 06:05:42,667 [kafka-monitor] DEBUG: Incremented total stats
2016-09-18 06:05:42,669 [kafka-monitor] DEBUG: Incremented plugin 'ScraperHandler' plugin stats
2016-09-18 06:05:42,670 [kafka-monitor] INFO: Added crawl to Redis
````

and get this error.
```
(sc) vagrant@scdev:/vagrant/crawler$ scrapy runspider crawling/spiders/manual.py
2016-09-18 05:58:06,864 [sc-crawler] INFO: Changed Public IP: None -> 121.44.110.101
<200 http://localhost:9312/properties/index_00000.html>
Exception RuntimeError: 'generator ignored GeneratorExit' in <generator object iter_errback at 0x7f2c2865c460> ignored
Unhandled error in Deferred:


Traceback (most recent call last):
  File "/home/vagrant/sc/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1194, in run
    self.mainLoop()
  File "/home/vagrant/sc/local/lib/python2.7/site-packages/twisted/internet/base.py", line 1203, in mainLoop
    self.runUntilCurrent()
  File "/home/vagrant/sc/local/lib/python2.7/site-packages/twisted/internet/base.py", line 825, in runUntilCurrent
    call.func(*call.args, **call.kw)
  File "/home/vagrant/sc/local/lib/python2.7/site-packages/twisted/internet/task.py", line 645, in _tick
    taskObj._oneWorkUnit()
--- <exception caught here> ---
  File "/home/vagrant/sc/local/lib/python2.7/site-packages/twisted/internet/task.py", line 491, in _oneWorkUnit
    result = next(self._iterator)
  File "/home/vagrant/sc/local/lib/python2.7/site-packages/scrapy/utils/defer.py", line 63, in <genexpr>
    work = (callable(elem, *args, **named) for elem in iterable)
  File "/home/vagrant/sc/local/lib/python2.7/site-packages/scrapy/core/scraper.py", line 183, in _process_spidermw_output
    self.crawler.engine.crawl(request=output, spider=spider)
  File "/home/vagrant/sc/local/lib/python2.7/site-packages/scrapy/core/engine.py", line 183, in crawl
    self.schedule(request, spider)
  File "/home/vagrant/sc/local/lib/python2.7/site-packages/scrapy/core/engine.py", line 189, in schedule
    if not self.slot.scheduler.enqueue_request(request):
  File "/vagrant/crawler/crawling/distributed_scheduler.py", line 361, in enqueue_request
    if not request.dont_filter and self.dupefilter.request_seen(request):
  File "/vagrant/crawler/crawling/redis_dupefilter.py", line 24, in request_seen
    c_id = request.meta['crawlid']
exceptions.KeyError: 'crawlid'
```

Can someone help with that error?

**Comment by madisonb** [comment]
Have you looked through the documentation [here](http://scrapy-cluster.readthedocs.io/en/latest/topics/crawler/extension.html) for an example of how to add your own spider? I agree if it is confusing or hard to add your own spider there should be improvement in the documentation. 

Without actually running your code, I presume this is the piece you are missing:
```
for key in response.meta.keys():
    req.meta[key] = response.meta[key]
```
Put that snippet into your `parse()` method. If you don't pass along these fields, the crawl identifiers or any other information you need are lost upon your first page scrape. The scheduler depends on these fields to do duplication filtering, which is what the error is above.

If this solves your problem please let me know and I will make a point to update the docs to better clarify that.

**Comment by madisonb** [comment]
That sounds like I good idea. If you would like to submit a PR with two new middlewares to make it easier to write a spider, I would be happy to help you merge it in. I think the passthrough of the meta fields is easier to figure out than the stats counters, so if you want to work on one or the other that would be great.

I am going to leave this open and mark it as something I want for 1.2.

**Comment by casertap** [comment]
Hi @madisonb Thanks for your answer.
I am a noob with scrapy and a noob with python so I do not think I can help you for now.
I am just experimenting right now and trying few different technologies.

**Comment by madisonb** [comment]
Closing, as this should be addressed with the two new middlewares.

**Comment by shenbakeshkishore** [comment]
Hi am trying to fetch the spider logs while using scrapy-cluster. I am using self._logger() for this purpose. Steps i followed:
1. Added this line of code in link_spider.py - "self._logger(response.url)"
2. sudo docker-compose up
3. Give a crawl request : curl localhost:5343/feed -H "Content-Type: application/json" -d '{"url":"https://www.facebook.com", "appid":"madisonTest", "crawlid":"123", "spiderid":"link"}'
4. Watching the "sudo docker-compose up" terminal. I see the crawl request being successfully pitched in and scraped successfully. But am not able to the see the log from the step 1 in the current terminal.

Please share your opinion. Thanks in advance.

**Comment by madisonb** [comment]
Hi @shenbakeshkishore,

You can view the documentation around the logger [here](https://scrapy-cluster.readthedocs.io/en/latest/topics/utils/logfactory.html). 

On first glance, it appears like you need to add the log level to your command, like `self._logger.info(<content>)`, but otherwise please raise a different issue on this project if your problem persists and you think it is a problem with the code in this repo.
