### ISSUE TITLE
The scrapy-cluster support redis cluster?

### ISSUE THREAD

**Issue by gongshaojie12** [istresearch/scrapy-cluster#97]

**Comment by madisonb** [comment]
Scrapy Cluster's core is based around [redis-py](https://github.com/andymccurdy/redis-py), which does not support cluster mode. In practice a single Redis instance is fast enough to handle almost all large scale operations.

**Comment by gongshaojie12** [comment]
Thanks

**Comment by mannmann2** [comment]
Is there any way to set up a cluster though? I'm looking for a way to prevent crawling failure if the redis node goes down.
