### ISSUE TITLE
Error running offline tests

### ISSUE THREAD

**Issue by vkchan** [istresearch/scrapy-cluster#99]
I got stuck with an error when running offline tests (<b>./run_offline_tests.sh</b>), the log file <b>test.log</b> was locked by the code when it is trying to delete it and Exception was thrown.

Please see: 
[Scrapy Clusters offline tests failed](http://stackoverflow.com/questions/42738367/scrapy-clusters-offline-tests-failed)

Really appreciate your help!

**Comment by madisonb** [comment]
@vkchan what is the operating system you are running on? Can you reproduce this in the `scdev` vagrant machine? Please also ensure that you have all the `requirements.txt` pip packages.

In your log you have 2 distinct errors
```
test_log_file_json (__main__.TestLogJSONFile) ... 2017-03-11 05:50:25,897 [test] INFO: Test log
ERROR
test_preserve_extra (__main__.TestLogJSONFile) ... 2017-03-11 05:50:26,877 [test] INFO: my message
ERROR
```
The code that is actually running is [here](https://github.com/istresearch/scrapy-cluster/blob/master/utils/tests/tests_offline.py#L177-L196), and there doesn't seem to be anything weird with the code. Do you have the proper permissions to read/write in the directory the code is in?

**Comment by vkchan** [comment]
@madisonb Thanks a lot for the quick response!

1. Unfortunately I won't be able to test it in vagrant machine, as I am running this in a virtualization instance of Ubuntu and I got errors due to nested virtualization (VT-x is not available).

2. I am running it on Ubuntu 16.04 LTS and I created the virtual environment using the attached <b>conda_env.yml</b> as follows:

```
conda env create -f conda_env.yml
source activate sc
```

3. I have full read/write permission to the folder, I did `chmod -R 777 .` and I still get the same errors when I ran the tests. I think the steps I took (as I described in my post at stackoverflow) seems to suggest the log file is locked, rather than a permission issue.

Thanks again!

**Comment by madisonb** [comment]
I will test with `16.04` right now in virtualbox, and if that works I will push up an additional Travis test to run all the unit and integration tests on 16.04 as well. If both of those are successful I can only presume it is something special to your environment.

If you are not doing lots of customizations, the docker containers for Scrapy Cluster [1.2](https://github.com/istresearch/scrapy-cluster/issues?q=milestone%3A%22Scrapy+Cluster+1.2%22) may be of help to you

**Comment by vkchan** [comment]
Thanks, I'm still trying to get vagrant running on my Ubuntu virtualization instance (timeout while waiting for the VM to boot)...

I'd be happy to try docker. Could you please point me to documentation on how I can set up the docker containers for Scrapy Cluster 1.2? I can only found the v1.1 doc on the web.

**Comment by madisonb** [comment]
The docs for 1.2 are located [here](http://scrapy-cluster.readthedocs.io/en/dev/), specifically the docker setup is [here](http://scrapy-cluster.readthedocs.io/en/dev/topics/advanced/docker.html). At the bottom of readthedocs you can switch versions by clicking on the `v: master` tab at the bottom, and flip over to `dev`

**Comment by vkchan** [comment]
I tried to follow the doc on docker setup, but have some issues:

1. I setup and verified docker and docker-compose are installed properly
2. I am stuck at step 3:

```
$ docker-compose up -d
ERROR: Couldn't connect to Docker daemon at http+docker://localunixsocket - is it running?
If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.

```

3. Do I need to create a virtual environment first? `conda env create -f docker-compose.yml` returned error.

Sorry I'm relatively new to docker, I couldn't get it up and running following the procedures and would appreciate if you can point me to the right direction. Thanks again!

**Comment by vkchan** [comment]
A related question: Apologies as I'm relatively new to docker, would I be able to use scrapy+selenium(chromedriver) if I go with the docker approach? The website I am trying to parse would only work if I use chromedriver. Thanks!

**Comment by madisonb** [comment]
I am not sure where your first comment went, but I would recommend reading the docker documentation for how to ensure your docker setup is correct, as it does not appear to be. It has a bit of a learning curve but your use case would certainly work within Docker. 

What you would do is create your spider, with all its configuration - containerize it and then run it. Just like the `link` spider is containerized, you can certainly create a container for your scrapy-selenium approach.

**Comment by vkchan** [comment]
Thanks a lot, I was finally able to get the docker containers of Scrapy Clusters 1.2 and successfully ran the "Your First Crawl" example in the doc.

I will read more about how to containerize it in Docker as you suggested, and try to deploy my spider as a docker. Thanks a lot for your help!

PS. I would be curious to know what I did wrong in the v1.1 Ubuntu cluster setup in case if you were able to reproduce my errors.

**Comment by madisonb** [comment]
I am unsure what happened. I have successfully ran everything in Ubuntu 16.04, and right now am trying to get it working in Travis CI as well just to triple check. 

Closing.
